"""Baked reference data for the Outreach → Reddit tracker.

Each row is a subreddit relevant to marketing a VR / music / rhythm game. Rows
carry only *reference* fields; team-editable tracking (status / last-posted /
notes) is overlaid at request time by `routers.outreach` from the persisted
store.

Data provenance / honesty note
------------------------------
Reddit hard-blocks automated access from our environment, so these rows were
assembled from third-party aggregators (freesubstats, redditli.st,
subredditstats, gummysearch, The Hive Index) and public marketing guides, not
from live subreddit pages. Two consequences the UI also surfaces:

* Subscriber counts are approximate snapshots for `SUBSCRIBERS_AS_OF`. Reddit
  additionally deprecated public member counts in favour of a rolling
  "Visitors" metric in 2025-26, so precise live numbers are no longer reliably
  obtainable. `subscribers_approx=True` flags every count we couldn't pin exact.
* `self_promo_verdict` / `self_promo_detail` capture the real rule where we
  could confirm it (e.g. r/SteamVR's developer flair, r/VRGaming's weekly
  Self-Promotion Saturday, r/Vive's historic dev bans, the music-maker subs'
  weekly-thread-only policy) and are otherwise a reasonable inference from
  community norms, marked "(inferred — verify)". ALWAYS click through to a
  sub's rules before posting; treat the verdict as a starting heuristic.

Row schema:
    name  url  category  subscribers  subscribers_approx
    self_promo_verdict  self_promo_detail  discord  description
"""
from __future__ import annotations

from typing import Any

# Snapshot date for every `subscribers` count below (ISO 8601).
SUBSCRIBERS_AS_OF = '2026-07-08'


def _row(
    name: str,
    category: str,
    subscribers: int,
    verdict: str,
    detail: str,
    description: str,
    *,
    approx: bool = True,
    discord: str | None = None,
) -> dict[str, Any]:
    return {
        'name': name,
        'url': f'https://www.reddit.com/{name}/',
        'category': category,
        'subscribers': subscribers,
        'subscribers_approx': approx,
        'self_promo_verdict': verdict,
        'self_promo_detail': detail,
        'discord': discord,
        'description': description,
    }


SEED_ROWS: list[dict[str, Any]] = [
    # ─── VR rhythm / music games (title-specific) ─────────────────────────
    _row('r/beatsaber', 'VR-Rhythm', 158946, 'Limited',
         'Flagship VR-rhythm community. Map-makers routinely share custom songs, but low-effort ads and unrelated commercial promo are removed — keep it community-relevant. (inferred — verify)',
         'The main community for Beat Saber, the best-known VR rhythm game.', approx=False),
    _row('r/beatsabermods', 'VR-Rhythm', 1500, 'Limited',
         'Modding / custom-song oriented; sharing mods, sabers and platforms is on-topic. Tag posts [PC] or [QUEST]. (inferred — verify)',
         'Beat Saber mods, custom sabers, platforms and custom songs.'),
    _row('r/PistolWhip', 'VR-Rhythm', 4500, 'Limited',
         'Small community for the VR rhythm-shooter; on-topic content and custom-scene sharing welcome, overt third-party ads should be relevant. (inferred — verify)',
         'Pistol Whip, a VR rhythm action-shooter by Cloudhead Games.'),
    _row('r/SynthRiders', 'VR-Rhythm', 18000, 'Limited',
         'Official news + player/mapper/modder community; use post flair. On-topic content welcome, unrelated promo discouraged. (inferred — verify)',
         'Synth Riders, a retrowave VR dance-rhythm game by Kluge Interactive.',
         discord='https://discord.com/invite/synthriders'),
    _row('r/AudioTrip', 'VR-Rhythm', 500, 'Limited',
         'Small community for a VR dance-rhythm title; choreography/custom-song sharing on-topic, blatant ads discouraged. (inferred — verify)',
         'Audio Trip, a VR dance-rhythm game (Kinemotik Studios).'),
    _row('r/Audica', 'VR-Rhythm', 1200, 'Limited',
         'Custom-map sharing on-topic; unrelated commercial promo discouraged. (inferred — verify)',
         "AUDICA, Harmonix's VR rhythm-shooter."),
    _row('r/OhShape', 'VR-Rhythm', 150, 'Unknown',
         'Very small community; no explicit self-promo rule found — verify with mods before posting promo.',
         "OhShape, a full-body 'hole in the wall' VR rhythm game."),
    _row('r/RagnarockVR', 'VR-Rhythm', 600, 'Limited',
         'Custom-song sharing on-topic. NB: r/Ragnarock is an unrelated magazine sub — the game sub is r/RagnarockVR. (inferred — verify)',
         'Ragnarock, a VR Viking rowing/drumming rhythm game.'),
    _row('r/UnpluggedVR', 'VR-Rhythm', 60, 'Unknown',
         'Fan-run "unofficial" community, very small; no explicit rule — verify before promoting.',
         'Unofficial community for Unplugged: Air Guitar, a hand-tracking VR guitar game.'),
    _row('r/DanceCentral', 'VR-Rhythm', 600, 'Unknown',
         'Franchise community covering classic + VR Dance Central; no explicit rule found — verify before promoting.',
         'The Dance Central franchise, including Dance Central VR (Harmonix).'),
    _row('r/SmashDrums', 'VR-Rhythm', 800, 'Limited',
         'Custom-chart / gameplay sharing on-topic; unrelated ads discouraged. (inferred — verify)',
         'Smash Drums, a VR drumming rhythm game.'),
    _row('r/Paradiddle', 'VR-Music', 700, 'Limited',
         'Official dev-run sub; bug reports, feature requests and cover-video sharing encouraged, unrelated promo discouraged. (inferred — verify)',
         'Paradiddle, a VR drum-kit / music-creation app.',
         discord='https://discord.gg/paradiddle'),
    _row('r/Electronauts', 'VR-Music', 250, 'Unknown',
         'Small community for a VR music-creation title; no explicit rule — verify before promoting.',
         'Electronauts, a Survios VR music-creation / DJ sandbox.'),
    _row('r/TribeXR', 'VR-Music', 400, 'Limited',
         'VR DJ community around creative expression and mentoring; sets/mixes and learning content on-topic, unrelated ads discouraged. (inferred — verify)',
         'Tribe XR, a VR DJ learning/performance app.'),
    _row('r/VirtuosoVR', 'VR-Music', 150, 'Unknown',
         'Small community for a VR music-creation app; no explicit rule — verify before promoting.',
         'Virtuoso, a VR music-creation / instrument sandbox app.'),
    _row('r/PowerBeatsVR', 'VR-Rhythm', 500, 'Unknown',
         'Small VR rhythm-fitness community; no explicit rule — verify before promoting.',
         'PowerBeatsVR, a VR rhythm-based fitness game.'),
    _row('r/FitXR', 'VR-Rhythm', 450, 'Unknown',
         'Community for the VR fitness app (formerly BoxVR); no explicit rule — verify before promoting.',
         'FitXR (formerly BoxVR), a rhythm-driven VR fitness app.'),
    _row('r/BoxVR', 'VR-Rhythm', 200, 'Limited',
         'Sidebar restricts posts to the game itself; fitness-challenge/playlist sharing encouraged. (inferred — verify)',
         'BoxVR, a boxing-based VR rhythm-fitness game (FitXR predecessor).'),
    _row('r/SupernaturalVR', 'VR-Rhythm', 6000, 'Limited',
         'Largely a member-support space for the subscription fitness app, so third-party promo likely discouraged. NB: r/Supernatural is the TV-show sub. (inferred — verify)',
         'Supernatural, the Meta/Within subscription VR rhythm-fitness app.'),
    _row('r/SpinRhythmXD', 'VR-Rhythm', 750, 'Limited',
         'Custom-chart and gameplay sharing on-topic; unrelated ads discouraged. (inferred — verify)',
         'Spin Rhythm XD, a rhythm game with a VR mode.'),
    _row('r/Thumper', 'VR-Rhythm', 2500, 'Unknown',
         "Community for the 'rhythm violence' game (with a VR mode); no explicit rule — verify before promoting.",
         "Thumper, a 'rhythm violence' game with a notable VR mode."),
    _row('r/GrooveGunner', 'VR-Rhythm', 150, 'Unknown',
         'Very small community; no explicit rule — verify with mods before promoting.',
         'Groove Gunner, a VR drumming/target rhythm game.'),

    # ─── General VR: hardware / platforms ─────────────────────────────────
    _row('r/virtualreality', 'VR-Hardware', 2100000, 'Limited',
         "The main general-VR hub and a key discovery channel for VR games. Enforces Reddit's ~9:1 anti-spam norm — a dev can share their own VR game, but blatant/repeated advertising is removed. (inferred — verify)",
         'General community for all things VR — headsets, games, and industry news.'),
    _row('r/oculus', 'VR-Hardware', 560000, 'Limited',
         "Large Oculus/Meta fan sub; follows Reddit's ~9:1 self-promo norm. Dev posts tolerated, ad-spam removed. (inferred — verify)",
         'Fan community for Oculus/Meta VR hardware and software.'),
    _row('r/OculusQuest', 'VR-Hardware', 659000, 'Limited',
         "Large Quest community; ~9:1 self-promo norm. Relevant Quest-game posts tolerated, blatant ads removed. (inferred — verify)",
         'The Meta (Oculus) Quest standalone VR headsets.', approx=False),
    _row('r/OculusQuest2', 'VR-Hardware', 99000, 'Limited',
         'Follows the same ~9:1 self-promo norm as sibling Quest subs. (inferred — verify)',
         'Dedicated to the Meta Quest 2 headset.', approx=False),
    _row('r/QuestPro', 'VR-Hardware', 15000, 'Unknown',
         'Small; no reliable rule data retrieved — verify before promoting.',
         "The Meta Quest Pro, Meta's high-end mixed-reality headset."),
    _row('r/OculusGo', 'VR-Hardware', 24000, 'Unknown',
         'Covers a discontinued headset and is largely inactive.',
         'The discontinued Oculus Go standalone VR headset.', approx=False),
    _row('r/SteamVR', 'VR-Hardware', 155987, 'Allowed',
         "Developer self-promotion is explicitly permitted using the dedicated 'self-promotion (developer)' post flair; ordinary spam is not tolerated.",
         "SteamVR, Valve's PC-VR runtime and platform.", approx=False),
    _row('r/Vive', 'VR-Hardware', 172005, 'ModApproval',
         'Historically very strict — mods banned VR devs (Onward, Rec Room, The Soulkeeper) for mentioning their own games, which pushed devs to r/vive_vr. Approach with caution / seek mod approval.',
         'Long-running community for the HTC Vive and PC-VR.', approx=False),
    _row('r/vive_vr', 'VR-Hardware', 12000, 'Allowed',
         'Founded 2023 as a developer-friendly alternative to r/Vive after its promo bans, so developer posts are welcomed.',
         'Breakaway HTC Vive / PC-VR community, welcoming to VR developers.'),
    _row('r/ValveIndex', 'VR-Hardware', 98253, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'The Valve Index PC-VR headset.', approx=False),
    _row('r/WindowsMR', 'VR-Hardware', 38383, 'Unknown',
         'Discontinued platform; no explicit rule found.',
         'The (discontinued) Windows Mixed Reality VR platform.', approx=False),
    _row('r/HPReverb', 'VR-Hardware', 17310, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'The HP Reverb / Reverb G2 Windows Mixed Reality headsets.', approx=False),
    _row('r/mixedreality', 'VR-Hardware', 4218, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'General mixed reality / VR-AR hardware and platforms.', approx=False),
    _row('r/pico4', 'VR-Hardware', 16000, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'The Pico 4 standalone VR headset.'),
    _row('r/PICO_VR', 'VR-Hardware', 2514, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'Pico VR headsets (ByteDance).', approx=False),
    _row('r/nreal', 'VR-Hardware', 14253, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'Nreal (now XREAL) AR/smart glasses.', approx=False),
    _row('r/XReal', 'VR-Hardware', 44867, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'XREAL (formerly Nreal) AR/smart glasses.', approx=False),
    _row('r/GoogleCardboard', 'VR-Hardware', 30687, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'Google Cardboard and mobile/phone-based VR viewers.', approx=False),
    _row('r/PSVR', 'VR-Hardware', 281418, 'Unknown',
         'PlayStation VR/PSVR2 console community; dev/game posts appear but are subject to general Reddit spam norms.',
         'Everything PlayStation VR (PS VR and PS VR2).', approx=False),
    _row('r/PSVR2', 'VR-Hardware', 120000, 'Unknown',
         'Dedicated PlayStation VR2 community; no explicit rule found — verify before promoting.',
         'The PlayStation VR2 headset, its games and news.'),

    # ─── VR gaming / social / dev ─────────────────────────────────────────
    _row('r/VRGaming', 'VR-Game', 185106, 'Limited',
         "Effectively zero tolerance for self-promo outside the weekly 'Self-Promotion Saturday' thread. (r/vrgaming is the same community — names are case-insensitive.)",
         'General VR gaming discussion community.', approx=False),
    _row('r/VirtualRealityGaming', 'VR-Game', 6000, 'Unknown',
         'No explicit self-promo rule found — verify before promoting.',
         'Small community for VR games, devices and news.'),
    _row('r/VRChat', 'VR-Social', 235888, 'Unknown',
         'Large social-VR platform community; no explicit self-promo rule found — verify before promoting.',
         'The social VR platform VRChat.', approx=False),
    _row('r/virtualrealitydev', 'VR-Dev', 2500, 'Allowed',
         "Purpose-built 'place for VR devs to learn and share' — project sharing is on-topic and unrestricted.",
         'Small community for VR developers to learn and share projects.'),
    _row('r/vrdev', 'VR-Dev', 9754, 'Allowed',
         'For developing games/apps for VR/AR/XR; sharing your own project is on-topic.',
         'Developing games and applications for VR/AR/XR.'),
    _row('r/OculusDev', 'VR-Dev', 5000, 'Allowed',
         'Developer-focused Oculus/Meta community; sharing your own app is on-topic. (inferred — verify)',
         'Small community for Oculus/Meta Quest VR developers.'),
    _row('r/Unity3D', 'VR-Dev', 468081, 'Limited',
         'Self-promo is a common post type and permitted, but subject to flair/quality rules and the ~10% norm; low-effort spam removed. Relevant — JamseshQuest is a Unity project.',
         'News, help and conversation about the Unity game engine.', approx=False),

    # ─── Flat-screen rhythm games ─────────────────────────────────────────
    _row('r/rhythmgames', 'Rhythm-Game', 90000, 'Limited',
         'General rhythm-game hub; devs may share their own game but must engage genuinely and follow the ~10% self-promo guideline. Ad-style spam removed. (inferred — verify)',
         'Community for all rhythm/music games (osu!, DDR, Clone Hero, etc.).',
         discord='https://discord.com/invite/6em38zhphC'),
    _row('r/osugame', 'Rhythm-Game', 334000, 'Limited',
         'Dedicated to osu!; promoting an unrelated rhythm game is usually treated as off-topic and removed. (inferred — verify)',
         'Community for the free-to-play rhythm game osu!.'),
    _row('r/GuitarHero', 'Rhythm-Game', 45000, 'Limited',
         'Franchise sub; off-topic self-promo discouraged, closely-related tools/content sometimes tolerated. (inferred — verify)',
         'Fan community for the Guitar Hero series.'),
    _row('r/Rockband', 'Rhythm-Game', 45000, 'Limited',
         'Franchise sub with a strong genre-audience match; unrelated promo may be removed, related custom-content tolerated. (count contested across aggregators; inferred — verify)',
         'Community for the Rock Band series and plastic-instrument rhythm games.'),
    _row('r/CloneHero', 'Rhythm-Game', 68000, 'Limited',
         'Centres on custom charts, tools and setups; genuinely relevant CH tools/charts welcomed, blatant spam removed. HIGH relevance — Jamsesh emits CH-style charts. (count contested; inferred — verify)',
         'Community for Clone Hero, the free Guitar Hero-style PC rhythm game.'),
    _row('r/YARG', 'Rhythm-Game', 3000, 'Limited',
         'Small community around the free open-source plastic-instrument game; related projects/tools generally welcome. HIGH relevance — CH-style charts. (inferred — verify)',
         'YARG (Yet Another Rhythm Game), a free open-source Guitar Hero-style game.'),
    _row('r/DanceDanceRevolution', 'Rhythm-Game', 18500, 'Limited',
         'Main DDR community; unrelated self-promo discouraged, DDR-relevant tools tolerated. (inferred — verify)',
         'The Dance Dance Revolution arcade/console series.'),
    _row('r/Stepmania', 'Rhythm-Game', 15400, 'Limited',
         'Open-source engine sub; custom simfiles/themes/tools are routinely shared, so relevant self-made content is generally welcome. (inferred — verify)',
         'StepMania, the open-source dance/rhythm game engine.'),
    _row('r/taikonotatsujin', 'Rhythm-Game', 19900, 'Limited',
         'Franchise community; unrelated self-promo discouraged, franchise-relevant content tolerated. (inferred — verify)',
         'The Taiko no Tatsujin drum rhythm game series.'),
    _row('r/projectDIVA', 'Rhythm-Game', 10600, 'Limited',
         'Unrelated game promotion typically off-topic. (inferred — verify)',
         'The Hatsune Miku: Project DIVA rhythm games.'),
    _row('r/MuseDash', 'Rhythm-Game', 18700, 'Limited',
         'Unrelated self-promo discouraged. (inferred — verify)',
         'Muse Dash, the anime-styled action rhythm game.'),
    _row('r/FridayNightFunkin', 'Rhythm-Game', 122000, 'Limited',
         'Large modding community; fan mods and self-made content commonly posted, but spam rules apply and promo should be FNF-relevant. (inferred — verify)',
         "Friday Night Funkin', the open-source rhythm game and its mods."),
    _row('r/adofai', 'Rhythm-Game', 2100, 'Limited',
         'Custom levels routinely shared, so relevant self-made content generally welcome. (inferred — verify)',
         'A Dance of Fire and Ice (ADOFAI), a one-button rhythm game.'),
    _row('r/Beatstar', 'Rhythm-Game', 25400, 'Limited',
         'Unrelated self-promo discouraged. (inferred — verify)',
         'Beatstar, the mobile tap rhythm game.'),
    _row('r/SoundVoltex', 'Rhythm-Game', 400, 'Limited',
         'Small community for SDVX; unrelated self-promo discouraged. (inferred — verify)',
         "SOUND VOLTEX (SDVX), KONAMI's arcade rhythm game."),
    _row('r/Cytus', 'Rhythm-Game', 19800, 'Limited',
         'Unrelated game promotion typically off-topic. (inferred — verify)',
         "Cytus / Cytus II, Rayark's mobile rhythm games."),
    _row('r/Deemo', 'Rhythm-Game', 4000, 'Limited',
         'Unrelated self-promo discouraged. (inferred — verify)',
         "Deemo, Rayark's story-driven piano rhythm game."),
    _row('r/arcaea', 'Rhythm-Game', 9800, 'Limited',
         'Unrelated game promotion typically off-topic. (inferred — verify)',
         "Arcaea, lowiro's mobile rhythm game."),
    _row('r/Phigros', 'Rhythm-Game', 6000, 'Limited',
         'Unrelated self-promo discouraged. (inferred — verify)',
         'Phigros, a free mobile rhythm game.'),
    _row('r/rhythmheaven', 'Rhythm-Game', 18900, 'Limited',
         'Unrelated self-promo discouraged, fan-made rhythm content sometimes welcomed. (inferred — verify)',
         'The Rhythm Heaven (Rhythm Tengoku) game series.'),
    _row('r/GrooveCoaster', 'Rhythm-Game', 2100, 'Limited',
         'Unrelated self-promo discouraged. (inferred — verify)',
         "Groove Coaster, Taito's rhythm game series."),
    _row('r/DJMAX', 'Rhythm-Game', 4500, 'Limited',
         'Unrelated self-promo discouraged. (inferred — verify)',
         'DJMAX Respect V and the DJMAX rhythm game series.'),
    _row('r/Quaver', 'Rhythm-Game', 300, 'Limited',
         'Free open-source VSRG; community-made content generally welcome. (inferred — verify)',
         'Quaver, a free open-source vertical-scrolling rhythm game.'),
    _row('r/Etterna', 'Rhythm-Game', 1700, 'Limited',
         'StepMania fork; custom content/tools routinely shared, so relevant self-made content generally welcome. (inferred — verify)',
         'Etterna, an open-source keyboard rhythm game (StepMania fork).'),
    _row('r/rocksmith', 'Rhythm-Game', 57000, 'Limited',
         'CDLC and tools are commonly discussed, so relevant self-made content is often tolerated within anti-spam norms. (inferred — verify)',
         'Rocksmith, the real-guitar learning/rhythm game.'),
    _row('r/beatmania', 'Rhythm-Game', 3000, 'Limited',
         'Unrelated self-promo discouraged. (inferred — verify)',
         'beatmania IIDX, KONAMI\'s arcade DJ rhythm game.'),
    _row('r/pumpitup', 'Rhythm-Game', 5300, 'Limited',
         'Unrelated self-promo discouraged. (inferred — verify)',
         'Pump It Up, Andamiro\'s dance/pump arcade rhythm game.'),
    _row('r/OsuMania', 'Rhythm-Game', 5300, 'Limited',
         'osu!mania mode community; unrelated self-promo typically off-topic. (inferred — verify)',
         'osu!mania, the vertical-scrolling key mode of osu!.'),

    # ─── Music games ──────────────────────────────────────────────────────
    _row('r/musicgames', 'Music-Game', 20000, 'Limited',
         'Small niche hub; sharing your own music game is tolerated if on-topic, but there is no dedicated promo thread and low-effort spam is removed. (inferred — verify)',
         'General hub for music and rhythm video games.'),
    _row('r/FortniteFestival', 'Music-Game', 25000, 'Limited',
         'Fan sub for the Rock Band-style mode; off-topic self-promo of unrelated games typically removed. Best for audience research, not direct promo. (inferred — verify)',
         "Community for Fortnite's Rock Band-style Festival music mode."),

    # ─── Music-maker / instrument communities (promo → weekly threads) ────
    _row('r/WeAreTheMusicMakers', 'Music-Community', 2000000, 'Limited',
         "Self-promo and 'check out my thing' posts are banned in the main feed — allowed only in the weekly Feedback/Promotion sticky threads. Craft discussion is fine.",
         'Large community for music producers and creators.'),
    _row('r/edmproduction', 'Music-Community', 424000, 'Limited',
         "Direct self-promo is banned in the feed; sharing your work is restricted to the weekly 'Feedback Friday' thread. Educational posts welcome.",
         'The craft of producing electronic dance music.', approx=False),
    _row('r/makinghiphop', 'Music-Community', 343000, 'Limited',
         "Self-promo and feedback are confined to the weekly 'Feedback Friday' and marketing/collab threads; standalone promo removed.",
         'Community for hip-hop producers and beatmakers.', approx=False),
    _row('r/musicproduction', 'Music-Community', 452000, 'Limited',
         'Self-promo limited to designated feedback threads; the feed is for production discussion, not promoting finished products.',
         'General music-production discussion community.'),
    _row('r/Guitar', 'Music-Community', 2100000, 'Limited',
         "No self-promo in the main feed; 'listen to my cover' content restricted to designated threads. Good for reaching guitar players.",
         'The largest general community for guitar players.'),
    _row('r/drums', 'Music-Community', 251000, 'Limited',
         "Promo / 'watch my video' posts generally limited to weekly threads or removed; discussion and gear talk are the norm. (inferred — verify)",
         'Community for drummers of all levels.'),
    _row('r/Bass', 'Music-Community', 350000, 'Limited',
         'Self-promo limited to designated threads; standalone promo of a product/channel typically removed. (inferred — verify)',
         'Community for bass guitar players.'),
    _row('r/piano', 'Music-Community', 900000, 'Limited',
         'Channel/app plugs restricted to designated threads; the feed centres on learning and performance. (inferred — verify)',
         'Community for pianists and keyboard players.'),
    _row('r/synthesizers', 'Music-Community', 471000, 'Limited',
         'Self-promo confined to the weekly self-promo/marketplace threads; direct product promo in the feed is removed.',
         'Synthesizer enthusiasts and electronic-instrument gear.', approx=False),
    _row('r/EDM', 'Music-Community', 3000000, 'Limited',
         'Self-promo heavily restricted and mostly funneled to weekly threads; the feed is for news and releases. Large but promo-averse.',
         'Large general community for electronic dance music fans.'),
    _row('r/DJs', 'Music-Community', 310000, 'Limited',
         'Mixes/gear/apps promo restricted to designated threads; standalone promo removed. (inferred — verify)',
         'DJs discussing gear, technique and the craft.'),
    _row('r/musictheory', 'Music-Community', 707000, 'Limited',
         'Self-promo restricted to a weekly self-promo thread; the feed is for theory questions and analysis.',
         'Discussing and learning music theory.', approx=False),
    _row('r/gamemusic', 'Music-Community', 138000, 'Limited',
         'Original tracks and self-promo must go in the weekly sticky thread; the feed is for OSTs, remixes and covers.',
         'Celebrating video-game music, OSTs, remixes and covers.'),
    _row('r/videogamemusic', 'Music-Community', 90000, 'Limited',
         'Sharing game music is on-topic, but promo of your own game/soundtrack should add value and follow the ~10% guideline. (inferred — verify)',
         'Sharing and discussing video-game soundtracks.'),
    _row('r/karaoke', 'Music-Community', 45000, 'Limited',
         'No prominent dedicated promo thread found; sharing a sing/karaoke game likely tolerated if genuinely relevant — lead with value. (inferred — verify)',
         'Karaoke fans, singers, and karaoke apps/games.'),
    _row('r/Melodics', 'Music-Community', 821, 'Unknown',
         'Small community for the practice app; no explicit self-promo rule confirmed — verify before promoting.',
         'Melodics, a rhythm-based instrument practice app.'),

    # ─── Indie / promo-friendly (where we can actually post) ──────────────
    _row('r/IndieGaming', 'Indie/Promo', 499880, 'Limited',
         'Posting your own indie game is common and on-topic, but the ~10% self-promo rule applies, posts require flair, and there are account-age/karma minimums plus contribution expectations.',
         'One of the main hubs for showcasing and discovering indie games.', approx=False),
    _row('r/indiegames', 'Indie/Promo', 235000, 'Allowed',
         'Posting your own indie game is a primary use of the sub; devs regularly share trailers, screenshots and demos. Follow flair rules, avoid duplicate spam.',
         'Indie-game showcase and discovery community.'),
    _row('r/gamedev', 'Indie/Promo', 2035976, 'Limited',
         'Direct promo in the main feed is discouraged; showcasing belongs in the recurring threads (Feedback Friday, Marketing Monday, Screenshot Saturday). Dev discussion welcome anytime.',
         'The largest game-development community.', approx=False,
         discord='https://discord.com/invite/reddit-gamedev'),
    _row('r/IndieDev', 'Indie/Promo', 413402, 'Allowed',
         'Sharing your own in-progress or released game is the point; self-promo and dev updates are welcome. Some days are themed (feedback/screenshot); flair required.',
         'Friendly community for indie devs to share their work and progress.', approx=False),
    _row('r/playmygame', 'Indie/Promo', 131000, 'Allowed',
         'Dedicated to posting your own game for others to play and give feedback — self-promo IS the purpose. A post template is required; reciprocal feedback encouraged.',
         'Sub built for devs to share their game and get people playing it.'),
    _row('r/DestroyMyGame', 'Indie/Promo', 33000, 'Allowed',
         'Brutal-feedback sub — posting your own trailer/gameplay for harsh critique is the entire point. You must submit something critiqueable (video), not just a store link.',
         "Blunt, critical feedback on your game's trailer/gameplay."),
    _row('r/gamedevscreens', 'Indie/Promo', 69000, 'Allowed',
         'Built for sharing screenshots and clips of your own game in development — posting your visuals is the purpose.',
         'Showcase for screenshots and short clips of games in development.', approx=False),
    _row('r/Screenshotsaturday', 'Indie/Promo', 90000, 'Allowed',
         'A weekly self-promo showcase for devs to post screenshots/GIFs of their own game; posting your work is expected. Centred on Saturdays.',
         'Weekly showcase where developers post screenshots of their own games.'),
    _row('r/SideProject', 'Indie/Promo', 735000, 'Allowed',
         'Dedicated to sharing your own side projects and micro-startups (incl. games/apps) — self-promo is the point. Show what you built.',
         'Makers sharing self-built side projects and startups.', approx=False),
    _row('r/IndieGameDevs', 'Indie/Promo', 115000, 'Allowed',
         'Sharing your own game, progress and feedback requests is welcome; follow flair rules, avoid pure spam.',
         'Indie game developers sharing work and getting feedback.'),
    _row('r/madewithunity', 'Indie/Promo', 100000, 'Allowed',
         'For showcasing projects/games built in Unity — sharing your own Unity game is on-topic. Especially relevant given JamseshQuest is a Unity client.',
         'Showcase for games and projects made with the Unity engine.'),
    _row('r/pcgaming', 'Indie/Promo', 4000000, 'Limited',
         'Strict self-promo policy: devs may post but must follow account-participation/disclosure rules and avoid repetitive store-link spam; violations removed. Effectively mod-approval-level scrutiny.',
         'Large PC-gaming news and discussion community.'),
    _row('r/Games', 'Indie/Promo', 3400000, 'Banned',
         "Curation-focused; direct self-promo is effectively banned outside specific mod-run recurring threads. Most dev self-posts are removed — not a practical direct-promo channel.",
         'High-signal gaming news/discussion sub with strict anti-promo curation.'),
    _row('r/gaming', 'Indie/Promo', 45000000, 'Limited',
         'Self-promo heavily restricted and enforced against the ~10% rule; most direct dev-promo is removed and only occasionally-viral clips survive. Huge reach, low success rate.',
         'The default massive general gaming subreddit.'),
]
